imports:
    - php

filter:
    paths: [PHPDaemon/*]

tools:
    # disable copy paste detector and simliarity analyzer as they have no real value
    # and a huge bunch of false-positives
    php_sim: false
    php_cpd: false

checks:
    php:
        deadlock_detection_in_loops: true