language: php

php:
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer self-update --quiet
  - COMPOSER_DISCARD_CHANGES=true composer --prefer-source update --no-interaction --no-progress

script:
  - ./vendor/bin/phpcs --standard=PSR2 --report=emacs --extensions=php --warning-severity=0 PHPDaemon/
